// arch sim testbench for TaskQueue (linklist_basic)
// Tests the native C++ model generated by `arch sim`
//
// Build & run:
//   cargo run -- sim tests/linklist_basic.arch --tb tests/linklist_basic_sim_tb.cpp
//
// Or manually:
//   g++ arch_sim_build/verilated.cpp arch_sim_build/VTaskQueue.cpp \
//       tests/linklist_basic_sim_tb.cpp -Iarch_sim_build -o sim_out && ./sim_out

#include "VTaskQueue.h"
#include <cassert>
#include <cstdio>
#include <vector>

static int g_tests  = 0;
static int g_passed = 0;

#define CHECK(cond, msg) do { \
    g_tests++; \
    if (cond) { g_passed++; } \
    else { fprintf(stderr, "FAIL [%s:%d] %s\n", __FILE__, __LINE__, msg); } \
} while(0)

// ── Clock helpers ────────────────────────────────────────────────────────────

struct DUT {
    VTaskQueue dut;

    void reset(int cycles = 2) {
        dut.rst = 1; dut.clk = 0;
        dut.alloc_req_valid = 0;
        dut.free_req_valid  = 0; dut.free_req_handle = 0;
        dut.insert_tail_req_valid = 0; dut.insert_tail_req_data = 0;
        dut.delete_head_req_valid = 0;
        dut.read_data_req_valid  = 0; dut.read_data_req_handle = 0;
        dut.write_data_req_valid = 0;
        dut.write_data_req_handle = 0; dut.write_data_req_data = 0;
        for (int i = 0; i < cycles * 2; i++) half_tick();
        dut.rst = 0;
    }

    void half_tick() { dut.clk ^= 1; dut.eval(); }
    // tick(): rising edge then falling edge; sample outputs after falling edge
    void tick() { half_tick(); half_tick(); }

    // alloc: latency 1 — resp fires same cycle as req
    uint32_t alloc_one() {
        dut.alloc_req_valid = 1;
        tick();
        uint32_t h = dut.alloc_resp_valid ? (uint32_t)dut.alloc_resp_handle : 0xFF;
        dut.alloc_req_valid = 0;
        tick();
        return h;
    }

    void free_one(uint32_t handle) {
        dut.free_req_valid = 1; dut.free_req_handle = handle;
        tick();
        dut.free_req_valid = 0; dut.free_req_handle = 0;
        tick();
    }

    // insert_tail: latency 2
    uint32_t insert_tail_one(uint32_t data) {
        dut.insert_tail_req_valid = 1; dut.insert_tail_req_data = data;
        tick(); // cycle 1: FSM grabs slot
        dut.insert_tail_req_valid = 0; dut.insert_tail_req_data = 0;
        tick(); // cycle 2: link update + resp fires
        uint32_t h = dut.insert_tail_resp_valid ? (uint32_t)dut.insert_tail_resp_handle : 0xFF;
        tick(); // clear
        return h;
    }

    // delete_head: latency 2
    uint32_t delete_head_one() {
        dut.delete_head_req_valid = 1;
        tick(); // cycle 1: latch data + slot
        dut.delete_head_req_valid = 0;
        tick(); // cycle 2: free slot + resp fires
        uint32_t d = dut.delete_head_resp_valid ? (uint32_t)dut.delete_head_resp_data : 0xDEAD;
        tick(); // clear
        return d;
    }

    // read_data: latency 1 — sample after first tick
    uint32_t read_data_one(uint32_t handle) {
        dut.read_data_req_valid = 1; dut.read_data_req_handle = handle;
        tick();
        uint32_t d = dut.read_data_resp_valid ? (uint32_t)dut.read_data_resp_data : 0xDEAD;
        dut.read_data_req_valid = 0; dut.read_data_req_handle = 0;
        tick();
        return d;
    }

    void write_data_one(uint32_t handle, uint32_t data) {
        dut.write_data_req_valid = 1;
        dut.write_data_req_handle = handle;
        dut.write_data_req_data  = data;
        tick();
        dut.write_data_req_valid = 0;
        tick();
    }
};

// ── Tests ────────────────────────────────────────────────────────────────────

static void test_initial_state(DUT& d) {
    d.reset();
    CHECK(d.dut.empty  == 1, "empty after reset");
    CHECK(d.dut.full   == 0, "not full after reset");
    CHECK(d.dut.length == 0, "length == 0 after reset");
    CHECK(d.dut.alloc_req_ready == 1, "alloc_req_ready after reset");
    printf("  test_initial_state ok\n");
}

static void test_alloc_free(DUT& d) {
    d.reset();
    uint32_t h = d.alloc_one();
    CHECK(h != 0xFF, "alloc returned a valid handle");
    CHECK(d.dut.length == 1, "length == 1 after alloc");
    d.free_one(h);
    CHECK(d.dut.length == 0, "length == 0 after free");
    printf("  test_alloc_free ok\n");
}

static void test_insert_delete_single(DUT& d) {
    d.reset();
    uint32_t h = d.insert_tail_one(0xABCD1234);
    CHECK(h != 0xFF, "insert_tail got handle");
    CHECK(d.dut.length == 1, "length == 1 after insert");
    uint32_t data = d.delete_head_one();
    CHECK(data == 0xABCD1234, "delete_head data correct");
    CHECK(d.dut.length == 0, "length == 0 after delete");
    CHECK(d.dut.empty  == 1, "empty after delete");
    printf("  test_insert_delete_single ok\n");
}

static void test_fifo_order(DUT& d) {
    d.reset();
    const uint32_t vals[4] = {10, 20, 30, 40};
    for (int i = 0; i < 4; i++) d.insert_tail_one(vals[i]);
    CHECK(d.dut.length == 4, "length == 4");
    for (int i = 0; i < 4; i++) {
        uint32_t got = d.delete_head_one();
        CHECK(got == vals[i], "FIFO order preserved");
    }
    CHECK(d.dut.empty == 1, "empty after drain");
    printf("  test_fifo_order ok\n");
}

static void test_fill_capacity(DUT& d) {
    d.reset();
    const int DEPTH = 8;
    for (int i = 0; i < DEPTH; i++) d.insert_tail_one(0x100 + i);
    CHECK(d.dut.full   == 1, "full after filling");
    CHECK(d.dut.length == DEPTH, "length == DEPTH");
    for (int i = 0; i < DEPTH; i++) {
        uint32_t got = d.delete_head_one();
        CHECK(got == (uint32_t)(0x100 + i), "drain order correct");
    }
    CHECK(d.dut.empty == 1, "empty after drain");
    printf("  test_fill_capacity ok\n");
}

static void test_read_write_data(DUT& d) {
    d.reset();
    uint32_t h = d.insert_tail_one(0xDEADBEEF);
    uint32_t rd = d.read_data_one(h);
    CHECK(rd == 0xDEADBEEF, "read_data returns inserted value");
    d.write_data_one(h, 0xCAFEBABE);
    rd = d.read_data_one(h);
    CHECK(rd == 0xCAFEBABE, "read_data returns written value");
    d.delete_head_one();
    printf("  test_read_write_data ok\n");
}

static void test_interleaved(DUT& d) {
    d.reset();
    d.insert_tail_one(1); d.insert_tail_one(2); d.insert_tail_one(3);
    CHECK(d.delete_head_one() == 1, "deq 1");
    d.insert_tail_one(4); d.insert_tail_one(5);
    CHECK(d.delete_head_one() == 2, "deq 2");
    CHECK(d.delete_head_one() == 3, "deq 3");
    CHECK(d.delete_head_one() == 4, "deq 4");
    CHECK(d.delete_head_one() == 5, "deq 5");
    CHECK(d.dut.empty == 1, "empty at end");
    printf("  test_interleaved ok\n");
}

// ── main ─────────────────────────────────────────────────────────────────────

int main() {
    DUT d;
    printf("=== TaskQueue arch sim tests ===\n");
    test_initial_state(d);
    test_alloc_free(d);
    test_insert_delete_single(d);
    test_fifo_order(d);
    test_fill_capacity(d);
    test_read_write_data(d);
    test_interleaved(d);
    printf("\n%d / %d tests passed\n", g_passed, g_tests);
    return (g_passed == g_tests) ? 0 : 1;
}
